travis:
  secure:
    BINSTAR_TOKEN: ngVIkOV+Oj/63zOYih5tKf4m0KZUVceW7upTSEGEhE8Kxm+odCeX+vIY1klJ19/nx065sV3/l6RlIQD3rzIFDNT2PTjds+4DEUIVDcD5pY9KAXkO9gvwBiDGiHMzVl/mMhfWkOBxzf7QtHepD+RplfMyl4I8Ig2SKysNd7OIYvPOAYl7VZSMQV1uWOCrOJGUuntnl3CFGs/chvmHmiQ96hr5+VdbyQv4auAPsq8c/AY8093DJ5EMhgBf5RlCs3KkV5Kzt5Hp3pDLkwmo1rhXsnsakcG1tUOSRR2pXuQbH5/ZVQ5ob3EmpAIem4NBCgNcb2TgWupIlaWk6iRuYuF95jOphqMuW53WZfBI2fdt3a3PYeRYL8uXwKvs2d8dt5cPq9gWb5HqmYvht7ieWz79ne06tZbuv1q0bSBXPcGfo94u3ALs73wPeYxRZiZDj67RHfYdtZgaoGIZnDJgPQzgAETaaCG7dBqEtDbs36uHqQy4fBMP6GFN/8XSEz32g5B73v9nYe92E+dRR/pSFD3hE08BW1UcYcuWW26F7fAI4OSRIZnKPi2G6J/Ka9YZjO1/fHqG0uVo1Ok4zE5LuibeNgbIhd6mbk0hmmccBTJCutDc9T3r7AGTeejIyv46IrkG9CFWbrGktnFKzzYbSfUczP9RBNJ/17o/Na1U71aV6dc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
