travis:
  secure:
    BINSTAR_TOKEN: MxM59TrcyN44eOPKyPjuIb0vlgHmtTuvPdMOBYVHlX0lJsKNraPe2HMPYGDo+vbTnPEQeDRQpPSA+pJHbSxlBOtVBSt0IQ6CBz5uTFlMsc14IW19weWFHp3UfaqzX0jQuWWEEqfNYFrAEEbDPkLHeLEUpXgsyquTXrMdvwD4f2fHUP+lY7EE7tqRwn0Cvwyb4FQgUa+RZR4hnOURoCoVDBV77LlWcIz5siwUrTyREApXgeUHm10m7O1uzC5hptfvZ4wVTSHGGMTk9Lym+4gKik05ZwV9c+oVmJ479yb2qDrE7M7H43/ol12sgo9Nzt9kGkW1gXZqFvAZk1eEwmWWsY+3G8YeiZRLTLa62jqi3AGtq/wWhuISC4DSJUYb+LJ+1DHebS6QA9fKXAN1t0fmOyMSJHvCzoLKpwetGWiuikImBW5owlbW4dOt/BFQq/RFh67WmQ9ahLJKyPepFjwb8j5q5Y78PAotX5aqrVgEdcw+VObVZtgvx+Isnj23DlhMLHBhYp2RN2YcpqhrHmqScRj1uZAXWsYTnhYnFl/tytmoK9icW82xl0/D8DLpEBazLDz7M3Q8mMwxc13mDJGWnv3AUg9LOc6EJ7CJegetq3b4u0tvsO7P7EhWMgfPBiS/fU7cMARHC5KT1cWoLAi7El+byKP/TrJvtbDzjR5yTK4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
