travis:
  secure:
    BINSTAR_TOKEN: HHykBtRCP/f/Lp8GcR8QiQinyhOh/kzAGNo3wj6X8x2SyNmYcvCIciDT3++shoSwKoxKcV5zlr+28NEF1nmgFqUH429jYOmAj/3kUaUhhliMptQ4ve73q5E/EKDo7c13K46uTyGxKL8UPnDtDDRZ1j9173I0Pw7t6NOXUxTmZT/v2HLsCoUqg830HTzhXBIgIUMKL/VEMqoFcy5C+6DFFJrhDrmK13kgNXc+wxFy72zIS9xYqdfsGExxWb51xPd6/tcUtBVbWfPQwuguaBowgHXVTgr91P+PF1+H5x9l1o7rU3LP0O6zFdFneZ/gImdvRuth8iOYjXMKLUPx9aqGiNwEsr+EctGFyPsxqdtSOD58Fx+VIPxY1EN7YhQCJxsd4MREKaRrbAz/lv16TzdbKGcrzksSUTwPuljbkNSeSMLHKMKCv15dtR6iADvLF930LbgTXAi1svgQBIspsS4VDcwaZqJb/KF/KO7GlsoVl0nSwvHwBbb+KGVhjcSNXLIDyJGggCP2zVuUvPkh4TNbyMAM41gmniPr1PUa1qIR8HXGkUcqMfztyrVFNvJnM2w1czHJn0F43HWCJ0UvS+0QTlZ97XAzAiA3QddluUtyTrakiwpczC10I6eaSXzTd9n2ZZoeCcm1krpZooNmMbRX0ZJ+k0QQKRdhx4U5d/X2khE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
